import { trainingServices, educationServices, subjects, guides } from '../data/expanded.js';
import { programs, learningSteps } from '../data/content.js';
import { esc, slug, url, icon, link, button, enquiryURL, pageHero, cta, checklist, card, accordion } from './templates.mjs';

export function serviceDirectory(file,items,folder){
 const symbols=folder==='corporate-training'?['spark','message','people','chart','workflow','book']:['book','pages','grid','workflow','cap'];
 return `<div class="service-directory">${items.map((item,i)=>`<article class="service-item"><div class="icon-circle">${icon(symbols[i]||'book')}</div><div><h3>${esc(item.short)}</h3><p>${esc(item.summary)}</p>${link(file,'Explore service',`${folder}/${item.slug}.html`)}</div></article>`).join('')}</div>`;
}
export function insightDirectory(file){
 return `<div class="article-list">${guides.map(g=>`<article class="article-row"><div class="article-meta">${esc(g.category)}<br>Practical guide</div><div><h2><a href="${url(file,`insights/${g.slug}.html`)}">${esc(g.title)}</a></h2><p>${esc(g.summary)}</p></div>${link(file,'Read guide',`insights/${g.slug}.html`)}</article>`).join('')}</div>`;
}
export async function writeExpanded(write){
 for(const [items,folder,type,hub] of [[trainingServices,'corporate-training','Corporate Training','corporate-training.html'],[educationServices,'education-solutions','Education Solutions','education-solutions.html']]){
  for(const item of items){
   const f=`${folder}/${item.slug}.html`;
   const siblings=items.filter(s=>s.slug!==item.slug).slice(0,3);
   await write(f,item.title,item.summary,`${pageHero(f,item.title,item.summary,{label:type,parent:[type,hub],actions:button(f,type==='Corporate Training'?'Discuss team training':'Discuss your project',enquiryURL(type))})}<section class="section"><div class="container service-detail-intro"><div><h2>${type==='Corporate Training'?'A considered approach to capability.':'Design around the learning purpose.'}</h2><p>${esc(item.intro)}</p><p>${esc(item.context)}</p></div><aside class="aside-list"><h2>Who this is for</h2><p>${esc(item.audience)}</p><h2>Related services</h2>${siblings.map(s=>`<a href="${url(f,`${folder}/${s.slug}.html`)}">${esc(s.short)}</a>`).join('')}</aside></div></section><section class="section scope-band"><div class="container intro-grid"><div><span class="section-label">Engagement scope</span><h2>What the ${type==='Corporate Training'?'learning':'project'} can cover.</h2><p>The final scope is agreed around your audience and requirements.</p></div><div>${checklist(item.coverage)}</div></div></section><section class="section"><div class="container outcome-panels"><div class="two-col"><div><h2>Define a useful result.</h2><p>Agree the intended outputs and review arrangements before the engagement begins.</p>${checklist(item.outputs)}</div><div><h2>Prepare for the discussion.</h2><p>${esc(item.prep)}</p><p>Include timing, location or format preferences, together with any technical, accessibility or information-handling requirements.</p>${link(f,'How we work','how-we-work.html')}</div></div></div></section><section class="section pale"><div class="container intro-grid"><h2>Scope, delivery & investment.</h2><div><p>Each engagement is quoted to reflect the agreed scope, preparation and delivery requirements. The proposal should identify inclusions, responsibilities, review points and commercial terms.</p><p>Availability, timing and any specific requirements are confirmed before acceptance.</p><div class="actions">${link(f,'Pricing & engagement options','pricing.html')}${link(f,`All ${type.toLowerCase()}`,hub)}</div></div></div></section>${cta(f,type==='Corporate Training'?'Discuss the capabilities your team needs.':'Discuss the learning resources you need.',item.prep,type,type==='Corporate Training'?'Request a proposal':'Discuss your project')}`);
  }
 }
 for(const subject of subjects){
  const f=`subjects/${subject.slug}.html`,matching=programs.filter(p=>p.category===subject.category);
  await write(f,subject.title+' Programs',subject.intro,`${pageHero(f,subject.title,subject.intro,{label:'Professional learning',parent:['Programs','programs.html']})}<section class="section"><div class="container intro-grid"><h2>A relevant starting point.</h2><div><p>${esc(subject.body)}</p><p>Explore a program area to see its intended audience, learning outcomes and outline. Enquire to confirm suitability, availability and the arrangements for participation.</p></div></div></section><section class="section pale"><div class="container"><div class="section-head"><h2>Explore the programs.</h2>${link(f,'All programs','programs.html')}</div><div class="program-grid${matching.length===3?' program-grid--three':''}">${matching.map(p=>card(f,p)).join('')}</div></div></section><section class="section"><div class="container intro-grid"><h2>For your organisation.</h2><div><p>A corporate learning engagement can connect the subject with your team’s roles, tools and operational priorities. Discuss the capability you want to develop and the audience involved.</p>${link(f,'Explore tailored team training',`corporate-training/${subject.team}.html`)}</div></div></section>${cta(f,'Find the right learning pathway.','Discuss an individual program or a learning requirement for your team.','Individual Program','Enquire about a program')}`);
 }
 for(const guide of guides){
  const f=`insights/${guide.slug}.html`;
  await write(f,guide.title,guide.summary,`${pageHero(f,guide.title,guide.summary,{label:guide.category,parent:['Insights','insights.html']})}<div class="container article-layout"><nav class="side-nav" aria-label="Article contents">${guide.sections.map(s=>`<a href="#${slug(s.title)}">${esc(s.title)}</a>`).join('')}</nav><article class="article-body">${guide.sections.map(s=>`<section id="${slug(s.title)}"><h2>${esc(s.title)}</h2><p>${esc(s.text)}</p>${s.list?`<ul>${s.list.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`:''}</section>`).join('')}<div class="split-note"><div><h3>Put the brief into a conversation.</h3><p>Discuss the learning requirements and next steps for your organisation.</p></div>${link(f,'Make an enquiry',enquiryURL(guide.cta))}</div></article></div><section class="section pale"><div class="container"><div class="section-head"><h2>Continue reading.</h2>${link(f,'All insights','insights.html')}</div><div class="internal-directory">${guides.filter(g=>g.slug!==guide.slug).slice(0,2).map((g,i)=>`<article class="directory-row"><span class="directory-number">0${i+1}</span><div><h3>${esc(g.title)}</h3><p>${esc(g.summary)}</p></div>${link(f,'Read guide',`insights/${g.slug}.html`)}</article>`).join('')}</div></div></section>`);
 }
 {
  const f='how-we-work.html';
  const steps=[['Understand the requirement','Define the audience, the capability need and the work the learning should support. Share the existing context, relevant material and any constraints.'],['Agree the engagement','Confirm the scope, objectives, deliverables, responsibilities and commercial arrangements in a written proposal. Clarify what is included before the work begins.'],['Develop the learning','Shape content and activities around the agreed objectives. Include the subject-matter input and review points required for a useful result.'],['Deliver and review','Complete the agreed training or resource handover. Review the work against the brief and consider appropriate next steps for continued application.']];
  await write(f,'How We Work','Our approach to scoping, designing and delivering professional learning and education engagements.',`${pageHero(f,'A clear process from the outset.','Understand the need, agree the scope and develop learning around a defined purpose.',{label:'How we work'})}<section class="section"><div class="container intro-grid"><h2>Begin with the requirement.</h2><div><p>A strong engagement starts with a shared understanding of what is needed. That includes the audience, the working context and the decisions the learning is intended to support.</p><p>The process can be adapted to an individual program, a corporate learning requirement or a defined education project. Its purpose is to make the work and responsibilities clear.</p></div></div></section><section class="section pale"><div class="container internal-directory">${steps.map(([title,text],i)=>`<article class="directory-row"><span class="directory-number">0${i+1}</span><div><h3>${title}</h3><p>${text}</p></div></article>`).join('')}</div></section><section class="section"><div class="container two-col"><div><h2>What to bring to the discussion.</h2>${checklist(['The audience and approximate participant count','The tasks or capabilities you want to develop','Any existing content, tools or internal policies','Your preferred timing and delivery context','The outcome you would like the engagement to support'])}</div><div><h2>What to confirm before acceptance.</h2>${checklist(['Scope, inclusions and deliverables','Roles and review responsibilities','Delivery arrangements and prerequisites','Full fees, applicable GST and payment terms','Cancellation conditions and permitted use of materials'])}</div></div></section>${cta(f,'Start with a clear brief.','Tell us about the work, the people and the capability you want to develop.','General Enquiry','Discuss your requirements')}`);
 }
 {
  const f='learning-approach.html';
  await write(f,'Our Learning Approach','A practical approach to professional learning: understand the concepts, apply them in context and reflect on the result.',`${pageHero(f,'Learning connected to professional practice.','Clear concepts, relevant activities and a considered approach to applying knowledge at work.',{label:'Our learning approach'})}<section class="section"><div class="container intro-grid"><h2>Build capability with purpose.</h2><div><p>Learning is easier to place in context when its purpose is clear. The audience should understand what a topic is intended to help them do and how it connects with their role.</p><p>Wisme’s approach centres on understanding, practical application and reflection. The emphasis and activities are shaped around the program’s objectives and the audience’s starting point.</p></div></div></section><section class="section pale"><div class="container internal-directory">${learningSteps.map(([title,text],i)=>`<article class="directory-row"><span class="directory-number">0${i+1}</span><div><h3>${title}</h3><p>${text}</p></div></article>`).join('')}</div></section><section class="section"><div class="container two-col"><div><h2>Relevant examples and activities.</h2><p>Examples should help participants connect a concept with familiar professional situations. Activities provide a way to examine an approach, make a decision or practise a defined task.</p><p>Appropriate human review is particularly important when working with AI or business information.</p></div><div><h2>A clear learning expectation.</h2><p>Program outcomes help define the intended areas of development. Confirm suitability, prerequisites, materials and any assessment or completion arrangements before participation.</p>${link(f,'Read about learning outcomes','insights/defining-learning-outcomes.html')}</div></div></section>${cta(f,'Find a relevant pathway.','Explore a program or discuss how learning can be shaped around your team.','Individual Program','Discuss your learning goals')}`);
 }
 {
  const f='for-individuals.html';
  await write(f,'Professional Learning for Individuals','Explore AI, data, automation and digital skills programs for your own professional development.',`${pageHero(f,'Develop the skills your work calls for.','Focused professional learning in AI, data and digital productivity, with clear routes into each subject.',{label:'For individuals',actions:button(f,'Explore all programs','programs.html')})}<section class="section"><div class="container intro-grid"><h2>Choose a useful starting point.</h2><div><p>You may be exploring a new subject, developing a tool you already use or looking for a clearer approach to everyday tasks. Start with the program area that connects most closely with your current work and interests.</p><p>Read the intended audience and learning outline, then enquire to confirm the appropriate starting point and available arrangements.</p></div></div></section><section class="section pale"><div class="container"><div class="section-head"><h2>Explore by subject.</h2></div><div class="internal-directory">${subjects.map((s,i)=>`<article class="directory-row"><span class="directory-number">0${i+1}</span><div><h3>${esc(s.title)}</h3><p>${esc(s.intro)}</p></div>${link(f,'Explore subject',`subjects/${s.slug}.html`)}</article>`).join('')}</div></div></section><section class="section"><div class="container two-col"><div><h2>Before you enrol.</h2>${checklist(['Confirm that the program is appropriate for your experience','Ask about the format, dates and duration','Check required software and learning materials','Confirm the full fee and applicable conditions'])}</div><div><h2>Continue developing.</h2><p>The Digital Skills Academy is being developed as a future ongoing learning offering. You can also discuss a specific subject or ask about the learning pathway most relevant to your goals.</p>${link(f,'Discover the Academy','academy.html')}</div></div></section>${cta(f,'Take the next step in your learning.','Share the skills you would like to develop and the context you work in.','Individual Program','Enquire about a program')}`);
 }
}
